### PR TITLE
Update badges

### LINKED ISSUE #30: 🚀 Release 0.1.0 (H_e) 📦
Master issue for the first release of ipyradiant. 

TODO 
* [x] merge pull#29
* [x] merge pull#23
* [x] Update screencast @zwelz3 (pull#32)
* [x] tag
* [x] pip release @nrbgt 
* [x] conda release @bollwyvl
* [x] update readme with install instructions, badges #39

### PR DESCRIPTION
**Pull request by zwelz3**
* [X] Update links and badges in [README](https://github.com/zwelz3/ipyradiant/blob/gh-update-badges/README.md) to match the style of ipyelk. 
* [x] Verify working after conda-forge is added

### CODE REVIEW

**Comment by nrbgt** [comment]
Since working on README: if there's any way you can resample the main screencast to not die on pypi.io that'd be swell... unfortunately, I don't know what the size limit is.

**Comment by nrbgt** [comment]
Looks like it's ~~5mb~~ 10MB

**Comment by zwelz3** [comment]
> Since working on README: if there's any way you can resample the main screencast to not die on pypi.io that'd be swell... unfortunately, I don't know what the size limit is.

Yeah I'll try and get to that soon.

**Comment by nrbgt** [comment]
Also can now add:
```
conda install -c conda-forge ipyradiant
```

**Comment by zwelz3** [comment]
Updated screencast (new size is ~6MB). Still not showing up on PyPI. Not sure if I need to trigger something, or will happen on next release?

**Comment by zwelz3** [comment]
> Also can now add:
> 
> ```
> conda install -c conda-forge ipyradiant
> ```
23058c4

**Review by nrbgt — APPROVED** [review]

**Pull request merged**
