### PR TITLE
Bump drawio, entropy, linting

### PR DESCRIPTION
**Pull request by nrbgt**
[binder](https://mybinder.org/v2/gh/nrbgt/ipyradiant/bump-drawio?urlpath=lab/tree/design/architecture/ideas.dio.svg)

- [x] duplicates some of the work from #11, where we found some issues related to drawio on windows. 
- [x] submodules to new fix schema issue temporarily (but still better),
- [x] add ui job to github actions to ensure we have a working ui at any given point
  - [x] fix some windows issues with processes dying and not returning
  - [x] add an extra wait function, in case node/webpack "apparently" dies really mysteriously, but still completes the build
- [x] disables extension manager and build checks

## testing
```
git clean -dxf
doit -n4 release lab
```

- the package should build
- Lab should start
- the drawing in `design/architecture` should appear when opened
  - don't worry about the semi-scary "Disconnected" header in the drawing, it's part of working on enabling synced editing between users

If something bad happens, kill everything off, and just run `doit release` and then `doit lab`, and post up a log of what happened... if it's long, or it might be hard to get personal details out, feel free to send it to me out-of-band.

### CODE REVIEW

**Comment by nrbgt** [comment]
It builds, but it doesn't show drawio... will be investigating...

**Comment by nrbgt** [comment]
Hopefully this (doubly) upstream fix works out, and we'll be good to go. Checking out on binder, and in a windows vm, too.

**Comment by nrbgt** [comment]
The osx fail is new to me, but I'm willing to accept it for now, unless someone with a mac wants to debug further.

**Comment by nrbgt** [comment]
Looking good on Linux, Windows VM and binder. I'll work around the OSX issue upstream on jupyterlab-drawio, but otherwise this is good to go. Would definitely appreciate someone giving this a go, will update with test procedure.

**Comment by zwelz3** [comment]
Yeah we can iron out mac issues later. Lukas is on mac so maybe he can dedicate some time down the road to investigate. 
I will review soon.

**Review by zwelz3 — APPROVED** [review]
Everything looks good to me. Glad to have this capability in the repo.

**Comment by nrbgt** [comment]
I'm just skipping the drawio clean, should be good now.

**Comment by nrbgt** [comment]
Or not. getting some weird merge behaviors. Might make a new branch/pr...

**Pull request closed without merging**
