### PR TITLE
Graph explorer widget

### LINKED ISSUE #74: Integrate initial graph explorer capabilities
With #61 introducing the `GraphExploreNodeSelection`, and #68 introducing the `InteractiveViewer`, this ticket scopes in the integration of these capabilities into a unified `GraphExplorer` widget. 

The widget should support the selection of nodes, their population in the viewer, and the successful execution of basic workflows for graph exploration. Selected nodes should have their data displayed via `ipywidgets.Output` using `IPython.display.JSON`. 

Blocked by #61 #68

### PR DESCRIPTION
**Pull request by zwelz3**
Adds the integrated graph explorer widget.

#### Test Procedure:
* Run the `GraphExplorer.ipynb` notebook
* Review the code
* checkout and `doit` if feeling thourough.

[Binder](https://mybinder.org/v2/gh/zwelz3/ipyradiant/graph-explorer-widget?urlpath=lab/tree/index.ipynb)

Blocked by #61 
Closes #74

### CODE REVIEW

**Comment by zwelz3** [comment]
TODO need to pull lukas/improved_vis before merge.

**Comment by nrbgt** [comment]
So I've gotten it back up to working browser stuff over on #84... we could:
- merge that in here (i can't retarget it)
- merge this first, then do more review

**Comment by zwelz3** [comment]
> So I've gotten it back up to working browser stuff over on #84... we could:
> 
> * merge that in here (i can't retarget it)
> * merge this first, then do more review

Lets merge this then do more. I'm working on another small patch PR based on comments from santiago.

**Review by nrbgt — COMMENTED** [review]
with the caveat that I have been testing with fixes for lab building, etc. on #84, lgtm

**Review by nrbgt — APPROVED** [review]

**Comment by zwelz3** [comment]
Not sure how conflicts appeared. Investigating now.

**Pull request merged**
