### PR TITLE
Add narrative, tests for example notebook

### LINKED ISSUE #19: Need tests for basic parsing of fixture files using rdflib.
rdflib has a number of parsers [see this link](https://rdflib.readthedocs.io/en/stable/plugin_parsers.html) but not all are installed in rdflib by default. The `guess_format` for graph loading allows all the parsers to be references even if they are not installed. 

This ticket scopes in a set of basic tests to ensure that fixtures exist for each format, and that the parsers are checked to ensure we know exactly what file formats our load widget should except. 

Any missing fixture formats should also be added (e.g. n3).

### PR DESCRIPTION
**Pull request by nrbgt**
[binder](https://mybinder.org/v2/gh/nrbgt/ipyradiant/gh-19-add-viz-test?urlpath=lab/tree/examples/Tab%20App%20Example.ipynb)

- fixes #19
- [x] adds importnb
  - [x] resolve env
- [x] makes notebook names a little more human readable (also not conflicting with library name)
  - [x] update README link
- [x] adds a test notebook
  - [x] can be interactively tested with point-click, once per format
  - [x] checks `IPYRADIANT_TESTING` when run headless, runs all the formats in one go
- [x] rework test tasks in dodo, one per file
  - [x] still runs all the notebook when testing, because importing
- [x] more path handling for windows with subprocess

Follow-on, as issues or PRs:
- [ ] investigate whether ipyctoscape performance can be improved for large graphs

### CODE REVIEW

**Comment by nrbgt** [comment]
Looks like the osx notebook test is just plain flaky. Not a lot we can do about it. Have rekicked, but likely we need to seek upstream for a better fix for how we want to use ipyctoscape.

**Comment by nrbgt** [comment]
K, back to green.

**Comment by zwelz3** [comment]
Running `doit release` and I get a bunch of these errors on nblint. 
```
.  lint:nblint
C:\git\ipyradiant\node_modules\.bin\prettier:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
C:\git\ipyradiant\node_modules\.bin\prettier:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
```
Not sure if this is bad or not.

**Comment by nrbgt** [comment]
yeah probably bad. will look into.

**Comment by zwelz3** [comment]
Also getting several dependency issues during `build:conda`. We have seen something similar before:
```
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.*, but conda is ignoring the .* and treating it as 3
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.23.*, but conda is ignoring the .* and treating it as 0.23
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
failed to parse packages from exception: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package setuptools conflicts for:
python[version='>=3.6'] -> pip -> setuptools
pip -> setuptools
rdflib-jsonld -> setuptools
ipywidgets -> ipython[version='>=4.0.0'] -> setuptools[version='>=18.5']

Package wincertstore conflicts for:
pip -> setuptools -> wincertstore[version='>=0.2']
rdflib-jsonld -> setuptools -> wincertstore[version='>=0.2']

Package urllib3 conflicts for:
pip -> requests -> urllib3[version='>=1.21.1,<1.22|>=1.21.1,<1.23|>=1.21.1,<1.24|>=1.21.1,<1.25|>=1.21.1,<1.26,!=1.25.0,!=1.25.1']
rdflib -> requests -> urllib3[version='>=1.21.1,<1.22|>=1.21.1,<1.23|>=1.21.1,<1.24|>=1.21.1,<1.25|>=1.21.1,<1.26,!=1.25.0,!=1.25.1']

Package pip conflicts for:
rdflib -> python[version='>=3.7,<3.8.0a0'] -> pip
ipywidgets -> python -> pip
pandas -> python[version='>=3.6,<3.7.0a0'] -> pip
python[version='>=3.6'] -> pip
qgrid -> python[version='>=3.8,<3.9.0a0'] -> pip
rdflib-jsonld -> python[version='>=3.8,<3.9.0a0'] -> pip
python_abi=3.8[build=*_cp38] -> python=3.8 -> pip
ipycytoscape[version='>=1.0.3'] -> python[version='>=3.0'] -> pip

Package vs2010_runtime conflicts for:
ipycytoscape[version='>=1.0.3'] -> python[version='>=3.0'] -> vs2010_runtime
pandas -> python=3.4 -> vs2010_runtime
pip -> python[version='>=3'] -> vs2010_runtime
ipywidgets -> python -> vs2010_runtime

Package certifi conflicts for:
rdflib-jsonld -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
rdflib -> requests -> certifi[version='>=2017.4.17']

Package python_abi conflicts for:
pandas -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp38|*_cp37m|*_cp36m']
rdflib -> requests -> python_abi=2.7[build=*_cp27m]
python_abi=3.8[build=*_cp38]
rdflib -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp37m|*_cp38']
ipywidgets -> ipykernel[version='>=4.5.1'] -> python_abi[version='2.7.*|3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp37m|*_cp38|*_cp27m']
rdflib-jsonld -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp37m|*_cp38']
qgrid -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp37m|*_cp38']

Package rdflib conflicts for:
rdflib
rdflib-jsonld -> rdflib[version='>=4.2|>=4.2.2']

Package webencodings conflicts for:
pip -> webencodings
python[version='>=3.6'] -> pip -> webencodings
rdflib -> html5lib -> webencodings

Package colorama conflicts for:
pip -> colorama
python[version='>=3.6'] -> pip -> colorama
ipywidgets -> ipython[version='>=4.0.0'] -> colorama

Package six conflicts for:
pip -> html5lib -> six[version='>=1.9']
ipywidgets -> traitlets[version='>=4.3.1,<5.0.0'] -> six
pandas -> python-dateutil[version='>=2.7.3'] -> six[version='>=1.5']
rdflib -> html5lib -> six[version='>=1.9']

Package ipaddress conflicts for:
ipywidgets -> notebook -> ipaddress
qgrid -> notebook[version='>=4.0.0'] -> ipaddress

Package ipywidgets conflicts for:
qgrid -> ipywidgets[version='>=7.0.0']
ipywidgets
ipycytoscape[version='>=1.0.3'] -> ipywidgets[version='>=7.5.0,<8.0.0']

Package ca-certificates conflicts for:
pandas -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
rdflib -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
ipywidgets -> python -> ca-certificates
pip -> python -> ca-certificates
rdflib-jsonld -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
qgrid -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
python[version='>=3.6'] -> openssl[version='>=1.1.1g,<1.1.2a'] -> ca-certificates

Package vs2008_runtime conflicts for:
rdflib -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime
pip -> python -> vs2008_runtime
ipywidgets -> python -> vs2008_runtime
pandas -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime[version='>=9.0.30729.1,<10.0a0']
rdflib-jsonld -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime
qgrid -> python[version='>=2.7,<2.8.0a0'] -> vs2008_runtime

Package pandas conflicts for:
pandas
qgrid -> pandas[version='>=0.17.0|>=0.18.0']

Package cachecontrol conflicts for:
pip -> cachecontrol
python[version='>=3.6'] -> pip -> cachecontrol

Package html5lib conflicts for:
rdflib-jsonld -> rdflib[version='>=4.2.2'] -> html5lib
python[version='>=3.6'] -> pip -> html5lib
rdflib -> html5lib
pip -> html5lib
Examining conflict for ipycytoscape pandas python_abi pip rdflib-jsonld qgrid rdflib python ipywidgets:   0%|
Examining conflict for ipycytoscape qgrid ipywidgets:  11%|█         | 1/9 [00:01<00:13,  1.67s/it]
Examining conflict for pandas pip rdflib-jsonld qgrid rdflib python ipywidgets:  44%|████▍     | 4/9 [00:03<00:04Examining conflict for pandas pip rdflib-jsonld qgrid rdflib python ipywidgets:  56%|█████▌    | 5/9 [00:03<00:02Examining conflict for pip ipywidgets pandas rdflib:  56%|█████▌    | 5/9 [00:05<00:02,  1.66it/s]
Examining conflict for pandas pip rdflib-jsonld qgrid rdflib python_abi ipywidgets:  67%|██████▋   | 6/9 [00:06<0Examining conflict for pandas pip rdflib-jsonld qgrid rdflib python_abi ipywidgets:  78%|███████▊  | 7/9 [00:06<0Examining conflict for pandas pip rdflib-jsonld qgrid rdflib ipywidgets:  78%|███████▊  | 7/9 [00:08<00:02,  1.13Examining conflict for pandas pip rdflib-jsonld qgrid rdflib ipywidgets:  89%|████████▉ | 8/9 [00:08<00:01,  1.29Examining conflict for pip rdflib:  89%|████████▉ | 8/9 [00:09<00:01,  1.29s/it]
DependencyError - taskid:release
ERROR: Task 'release' checking dependencies: Dependent file 'C:\git\ipyradiant\dist\conda-bld\noarch\ipyradiant-0.1.0-py_0.tar.bz2' does not exist.
```

**Comment by nrbgt** [comment]
dunno, try `conda clean -yaf`?

**Comment by nrbgt** [comment]
Linux cache fail looks spurious...

**Comment by zwelz3** [comment]
> dunno, try `conda clean -yaf`?

`git clean -dfx` and `conda clean -yaf` still getting the dependency errors for conda build. 🤷

**Comment by nrbgt** [comment]
dunno, try `conda clean -yaf`?

**Comment by nrbgt** [comment]
Yeah, I have been unable to determine/reproduce the issue you are seeing with `conda-build`.

perhaps try generating a new `base` from `.ci/environment.yml` and using that?

**Comment by zwelz3** [comment]
Yeah idk, still having the issue. @lukasnijhawan can you try running this PR and seeing if you have any issues on your windows box?

**Comment by zwelz3** [comment]
FYI `doit lab` works for me, but the error is on `doit release`.

**Comment by lnijhawan** [comment]
@zwelz3 I was able to run doit lab and doit release, no errors

**Comment by zwelz3** [comment]
> @zwelz3 I was able to run doit lab and doit release, no errors

Good enough for me.

**Pull request merged**
