### PR TITLE
21: Add index.ipynb landing page for lab

### LINKED ISSUE #21: Add index page for notebook examples
For now, will use normal notebook hyperlinks to develop an index landing page that categorizes examples. 
In the future, may want to move to something more like [Jupyter{book}](https://jupyterbook.org/intro.html).

### PR DESCRIPTION
**Pull request by zwelz3**
- fixes #21 
- [demo](https://mybinder.org/v2/gh/jupyrdf/ipyradiant/21-examples-index-page?urlpath=lab/tree/index.ipynb) 
- [X] Add index.ipynb landing page with links to examples
- [X] Update binder and CONTRIBUTING
- [X] Update jupyrdf org icon in assets

### CODE REVIEW

**Comment by nrbgt** [comment]
Trying on binder: recall this is what you get if you get unlucky and have to wait for the build:
Screenshot from 2020-08-07 11-24-00

... so it's important that above-the-fold stuff has a lot of punch... getting a screenshot in there would be good

**Comment by zwelz3** [comment]
@nrbgt what type of screenshot are you thinking for the `index.ipynb`? Maybe a screenshot of the tab app?

**Comment by nrbgt** [comment]
You may just want to fall back to raw html for the logo, something like:
```html
<img style="float: left" src="./assets/whatever.svg.png.gif" width="100" height="100"/>
```
This will also be a good place to put stuff generated by `drawio`... we can save things as `.dio.svg` and get the first page for "free" in the browser, etc.

**Comment by zwelz3** [comment]
> You may just want to fall back to raw html for the logo, something like:
> 
> ```
> 
> ```
> 
> This will also be a good place to put stuff generated by `drawio`... we can save things as `.dio.svg` and get the first page for "free" in the browser, etc.

How is that HTML different than what I put in the notebook? I think I am missing something.

**Comment by nrbgt** [comment]
Further, on the assets, we should consider having an "official" home for them in e.g. `jupyrdf/jupyrdf.github.io`, which would automatically get published to https://jupyrdf.github.io

I've often found it easiest to get this started using the built-in Jekyll templater, then graduating to readthedocs at a later date.

**Comment by nrbgt** [comment]
Just saying, checking how it looks, 
https://nbviewer.jupyter.org/github/jupyrdf/ipyradiant/blob/21-examples-index-page/index.ipynb


(and also on the binder loading screen)

**Comment by nrbgt** [comment]
Something like:
Screenshot from 2020-08-07 11-33-43

**Review by nrbgt — APPROVED** [review]
LGTM

**Comment by nrbgt** [comment]
Another hack might be to add the existing drawio: in markdown:
```md
## Architecture

![](./design/architecture/ideas.dio.svg)
```


Screenshot from 2020-08-07 12-09-40

**Comment by nrbgt** [comment]
Or even this, which clicks right into the document (editable):

```md
## Architecture

[![][ideas][]][ideas]

[ideas]: ./design/architecture/ideas.dio.svg
```

**Comment by zwelz3** [comment]
> You may just want to fall back to raw html for the logo, something like:
> 
> ```
> 
> ```
> 
> This will also be a good place to put stuff generated by `drawio`... we can save things as `.dio.svg` and get the first page for "free" in the browser, etc.

Addressed in 1d7f248
I really like how clean this is, but I moved it to the right so that it looks almost justified. 
I also added the initial WIP architecture diagram. ~~I don't think it is _that_ useful yet, but we don't have much info in the index file anyways.~~ I think it is useful to show how we plan on moving the architecture forward.

**Comment by zwelz3** [comment]
Can check updates on binder preview. Going to merge on green CI

**Pull request merged**
